# Generated by Django 3.2.4 on 2021-08-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('value', models.CharField(default='', max_length=1000)),
                ('icon', models.CharField(default='', max_length=50)),
                ('iconPosition', models.CharField(default='left', max_length=10)),
                ('color', models.CharField(default='primary2', max_length=10)),
                ('shape', models.CharField(default='rounded', max_length=10)),
                ('disabled', models.BooleanField(default=False)),
                ('class_name', models.CharField(default='', max_length=100)),
                ('typ_color', models.CharField(default='main', max_length=20)),
                ('variant', models.CharField(default='h1', max_length=20)),
                ('tag', models.CharField(default='default', max_length=20)),
                ('text', models.TextField(default='')),
                ('spacingBottom', models.CharField(default='m', max_length=10)),
                ('spacingTop', models.CharField(default='m', max_length=10)),
                ('spacing', models.CharField(default='m', max_length=5)),
                ('label', models.CharField(default='Label', max_length=200)),
                ('hint', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='Assistive title', max_length=200)),
                ('default_open', models.BooleanField(default=False)),
                ('fill', models.CharField(default='default', max_length=20)),
                ('size', models.IntegerField(default=24)),
                ('checked', models.BooleanField(default=False)),
                ('text_position', models.CharField(default='right', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SelectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(default=1)),
                ('value', models.CharField(default='Select item', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TabItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=1)),
                ('value', models.TextField(default='')),
                ('icon', models.CharField(default='', max_length=50)),
                ('iconPosition', models.CharField(default='left', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('blocks', models.ManyToManyField(related_name='row_blocks', to='main.Block')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='select_items',
            field=models.ManyToManyField(related_name='block_select_items', to='main.SelectItem'),
        ),
        migrations.AddField(
            model_name='block',
            name='tab_items',
            field=models.ManyToManyField(related_name='block_tab_items', to='main.TabItem'),
        ),
        migrations.AddField(
            model_name='page',
            name='rows',
            field=models.ManyToManyField(related_name='page_rows', to='main.Row'),
        ),
    ]
