# Generated by Django 3.2.4 on 2021-08-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210820_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='cols',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='block',
            name='depth',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='block',
            name='type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
