# Generated by Django 3.2.4 on 2021-08-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210820_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='box_children',
            field=models.ManyToManyField(blank=True, related_name='_main_block_box_children_+', to='main.Block'),
        ),
        migrations.AlterField(
            model_name='block',
            name='checked',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='block',
            name='class_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='block',
            name='color',
            field=models.CharField(blank=True, default='primary2', max_length=10),
        ),
        migrations.AlterField(
            model_name='block',
            name='default_open',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='block',
            name='depth',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='block',
            name='disabled',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='block',
            name='fill',
            field=models.CharField(blank=True, default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='block',
            name='hint',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='block',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='block',
            name='iconPosition',
            field=models.CharField(blank=True, default='left', max_length=10),
        ),
        migrations.AlterField(
            model_name='block',
            name='label',
            field=models.CharField(blank=True, default='Label', max_length=200),
        ),
        migrations.AlterField(
            model_name='block',
            name='select_items',
            field=models.ManyToManyField(blank=True, related_name='block_select_items', to='main.SelectItem'),
        ),
        migrations.AlterField(
            model_name='block',
            name='shape',
            field=models.CharField(blank=True, default='rounded', max_length=10),
        ),
        migrations.AlterField(
            model_name='block',
            name='size',
            field=models.IntegerField(blank=True, default=24),
        ),
        migrations.AlterField(
            model_name='block',
            name='spacing',
            field=models.CharField(blank=True, default='m', max_length=5),
        ),
        migrations.AlterField(
            model_name='block',
            name='spacingBottom',
            field=models.CharField(blank=True, default='m', max_length=10),
        ),
        migrations.AlterField(
            model_name='block',
            name='spacingTop',
            field=models.CharField(blank=True, default='m', max_length=10),
        ),
        migrations.AlterField(
            model_name='block',
            name='tab_items',
            field=models.ManyToManyField(blank=True, related_name='block_tab_items', to='main.TabItem'),
        ),
        migrations.AlterField(
            model_name='block',
            name='tag',
            field=models.CharField(blank=True, default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='block',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='block',
            name='text_position',
            field=models.CharField(blank=True, default='right', max_length=10),
        ),
        migrations.AlterField(
            model_name='block',
            name='title',
            field=models.CharField(blank=True, default='Assistive title', max_length=200),
        ),
        migrations.AlterField(
            model_name='block',
            name='typ_color',
            field=models.CharField(blank=True, default='main', max_length=20),
        ),
        migrations.AlterField(
            model_name='block',
            name='value',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='block',
            name='variant',
            field=models.CharField(blank=True, default='h1', max_length=20),
        ),
    ]
