# Generated by Django 3.2.4 on 2021-08-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210820_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='sizeElem',
            field=models.CharField(blank=True, default='medium', max_length=10),
        ),
    ]
