# Generated by Django 3.2.4 on 2021-08-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_block_sizeelem'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='corners_rounding',
            field=models.CharField(default='m', max_length=20),
        ),
    ]
