# Generated by Django 3.2.4 on 2021-08-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_block_corners_rounding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='box_children',
            field=models.ManyToManyField(blank=True, related_name='block_box_children', to='main.Row'),
        ),
    ]
