# Generated by Django 3.2.4 on 2021-08-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_block_box_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='box_children',
            field=models.ManyToManyField(blank=True, default=None, related_name='block_box_children', to='main.Row'),
        ),
        migrations.AlterField(
            model_name='row',
            name='blocks',
            field=models.ManyToManyField(blank=True, related_name='row_blocks', to='main.Block'),
        ),
    ]
