# Generated by Django 3.2.4 on 2021-08-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_block_global_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='offset',
            field=models.IntegerField(default=0),
        ),
    ]
