# Generated by Django 3.2.4 on 2021-08-21 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_block_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='row',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.row'),
        ),
        migrations.AddField(
            model_name='row',
            name='colsLasted',
            field=models.IntegerField(default=12),
        ),
    ]
